---
title: ""
author: 
subtitle: ''
output:
  html_document:
    css: web_report.css
    self_contained: false
  pdf_document: default
params:
  geography: US
---

```{=html}
<!-- this calls Lato font --> 
<style>
@import url('https://fonts.googleapis.com/css?family=Lato&display=swap');
</style>
```

```{=html}
<!-- this calls crucial iframe resizing script --> 
<script type="text/javascript" src="https://apps.urban.org/features/dataviz-libs/pym-js/v1.3.2/pym.nprapps.org_pym.v1.min.js">
</script>

<script>
var pymChild = new pym.Child({ polling: 500 });
</script>
```

```{r rmarkdown-setup, echo=FALSE}
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(echo = FALSE)
```

```{r r-setup, echo=FALSE}
library(tidyverse)
library(urbnthemes)
library(gt)
library(gtExtras)

set_urbn_defaults(style = "print")
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

# Analysis of `r params$geography`

<div class="over-table-spacing"></div>

```{r r-data, echo=FALSE}
national_bystate <- data.table::fread("data/processed/national_bystate.csv")
national_bysize <- data.table::fread("data/processed/national_bysize.csv")
national_bysubsector <- data.table::fread("data/processed/national_bysubsector.csv")
```

## {.tabset}

### State
```{r}
national_bystate  |> mutate(State = factor(
  State,
  levels = c(
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "District of Columbia",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Other U.S. Territories",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
    "Other US Jurisdictions/Unmapped",
    "Total"
  )
)) |>
  arrange(State) |>
  dplyr::mutate(color = "") |>
  gt() |>
  data_color(
    columns = `Share of 990 Filers w/ Gov Grants at Risk`,
    target_columns = color,
    method = "auto",
    palette = c(
      "#FFF2CF",
      "#FCE39E",
      "#FDD870",
      "#FCCB41",
      "#FDBF11",
      "#E88E2D",
      "#CA5800",
      "#843215"
    )
  ) |>
  cols_width(color ~ px(5)) |>
  cols_label(color = "") |>
  cols_align(align = "left", columns = c("State")) |>
  tab_style(
    style = cell_borders(
      sides = "right",
      color = "#d2d2d2",
      weight = px(1)
    ),
    locations = cells_body(columns = 1)
  ) |>
  tab_style(
    style = cell_text(weight = "bold"),
    locations = list(cells_body(columns = 1), cells_column_labels())
  ) |>
  tab_options(table.border.top.style = "hidden",
              data_row.padding = px(10))
```

### Size
```{r}
national_bysize |> mutate(Size = factor(
  Size,
  levels = c(
    "Less than $100K",
    "Between $100K and $499K",
    "Between $500K and $999K",
    "Between $1M and $4.99M",
    "Between $5M and $9.99M",
    "Greater than $10M",
    "Total"
  )
)) |>
  arrange(Size) |>
   dplyr::mutate(color = "") |>
  gt() |>
  data_color(
    columns = `Share of 990 Filers w/ Gov Grants at Risk`,
    target_columns = color,
    method = "auto",
    palette = c("#FFF2CF", "#FCE39E", "#FDD870", "#FCCB41", "#FDBF11", "#E88E2D", "#CA5800", "#843215")
    ) |>
    cols_width(color ~ px(5)) |>
  cols_label(
    color = ""  # This sets the column name to an empty string
) |>
  cols_align(
    align = "left",
    columns = c("Size")
  ) |>
  tab_style(
    style = cell_borders(
      sides = "right",
      color = "#d2d2d2",
      weight = px(1)
    ),
    locations = cells_body(
      columns = 1
    )
  ) |>
  tab_style(
    style = cell_text(weight = "bold"),
    locations = list(
      cells_body(columns = 1),  # First column
      cells_column_labels()      # All headers
    )
  ) |>
  tab_options(
    table.border.top.style = "hidden",
    data_row.padding = px(10)
  )
```

### Subsector
```{r}
national_bysubsector |> mutate(Subsector = factor(
  Subsector,
  levels = c(
    "Arts, Culture, and Humanities",
    "Education (Excluding Universities)",
    "Environment and Animals",
    "Health (Excluding Hospitals)",
    "Hospitals",
    "Human Services",
    "International, Foreign Affairs",
    "Mutual/Membership Benefit",
    "Public, Societal Benefit",
    "Religion Related",
    "Universities",
    "Unclassified",
    "Total"
  )
)) |>
  arrange(Subsector) |>
  dplyr::mutate(color = "") |>
  gt() |>
  data_color(
    columns = `Share of 990 Filers w/ Gov Grants at Risk`,
    target_columns = color,
    method = "auto",
    palette = c(
      "#FFF2CF",
      "#FCE39E",
      "#FDD870",
      "#FCCB41",
      "#FDBF11",
      "#E88E2D",
      "#CA5800",
      "#843215"
    )
  ) |>
  cols_width(color ~ px(5)) |>
  cols_label(color = "") |>
  cols_align(align = "left", columns = c("Subsector")) |>
  tab_style(
    style = cell_borders(
      sides = "right",
      color = "#d2d2d2",
      weight = px(1)
    ),
    locations = cells_body(columns = 1)
  ) |>
  tab_style(
    style = cell_text(weight = "bold"),
    locations = list(cells_body(columns = 1), cells_column_labels())
  ) |>
  tab_options(table.border.top.style = "hidden",
              data_row.padding = px(10))
                
```

## {-}

###### **Source**: *National Center for Charitable Statistics [2021 501(c)(3) Charities PZ Scope](https://urbaninstitute.github.io/nccs/catalogs/catalog-core.html), [2021 Efilers](https://nccs.urban.org/nccs/catalogs/catalog-efile.html) and [Unified  BMF](https://nccs.urban.org/nccs/datasets/bmf/)*

###### **Notes**: *Disclaimers about the data.*