---
title: ""
author: 
subtitle: ''
output:
  html_document:
    css: web_report.css
    self_contained: false
  pdf_document: default
params:
  state: California
---

```{=html}
<!-- this calls Lato font --> 
<style>
@import url('https://fonts.googleapis.com/css?family=Lato&display=swap');
</style>
```

```{=html}
<!-- this calls crucial iframe resizing script --> 
<script type="text/javascript" src="https://apps.urban.org/features/dataviz-libs/pym-js/v1.3.2/pym.nprapps.org_pym.v1.min.js">
</script>

<script>
var pymChild = new pym.Child({ polling: 500 });
</script>
```

```{r rmarkdown-setup, echo=FALSE}
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(echo = FALSE)
```

```{r r-setup, echo=FALSE}
library(tidyverse)
library(urbnthemes)
library(gt)
library(gtExtras)
library(stringr)
library(epoxy)

set_urbn_defaults(style = "print")
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

## `r params$state` - Financial Risk of Nonprofits Losing Government Grants

<div class="over-table-spacing"></div>


```{r load-data, echo=FALSE}
setwd(rprojroot::find_rstudio_root_file())
source("R/format_percentages.R")
source("R/format_districts.R")

state <- gsub(" ", "-", tolower(params$state))

county <- data.table::fread(sprintf("data/processed/state_factsheets/%s_bycounty.csv", 
                                    state))
district <- data.table::fread(sprintf("data/processed/state_factsheets/%s_bydistrict.csv",
                                      state))
size <- data.table::fread(sprintf("data/processed/state_factsheets/%s_bysize.csv", 
                                  state))
subsector <- data.table::fread(sprintf("data/processed/state_factsheets/%s_bysubsector.csv",
                                       state))
```

```{r into-para, echo=FALSE}
state_title <- params$state
total_govgrants <- size |>
  dplyr::filter(Size == "Total") |>
  dplyr::pull(`Total government grants ($)`)

total_govgrants <- gsub(
  "[$,]", "", total_govgrants)
total_govgrants <- as.numeric(total_govgrants)
total_govgrants <- scales::label_number(accuracy=0.1, scale_cut=scales::cut_short_scale())(total_govgrants)

topcounties_grants <- county |>
  dplyr::filter(Geography != params$state, Geography != "United States") |>
  dplyr::mutate(govfunding = as.numeric(gsub("[$,]", "", `Total government grants ($)`))) |>
  dplyr::arrange(desc(govfunding)) |>
  dplyr::slice_head(n = 3) |>
  dplyr::pull(Geography)

topdistricts_grants <- district |>
  dplyr::filter(Geography != params$state, Geography != "United States") |>
  dplyr::mutate(govfunding = as.numeric(gsub("[$,]", "", `Total government grants ($)`))) |>
  dplyr::arrange(desc(govfunding)) |>
  dplyr::slice_head(n = 3) |>
  dplyr::pull(Geography)

topcounties_surplus <- county |>
  dplyr::filter(Geography != params$state, Geography != "United States") |>
  dplyr::mutate(govfunding = as.numeric(
    gsub("[%]", "", `Operating surplus without government grants (%)`)
  )) |>
  dplyr::arrange(govfunding) |>
  dplyr::slice_head(n = 3) |>
  dplyr::pull(Geography)

topdistricts_surplus <- district |>
  dplyr::filter(Geography != params$state, Geography != "United States") |>
  dplyr::mutate(govfunding = as.numeric(
    gsub("[%]", "", `Operating surplus without government grants (%)`)
  )) |>
  dplyr::arrange(govfunding) |>
  dplyr::slice_head(n = 3) |>
  dplyr::pull(Geography)

topcounties_atrisk <- county |>
  dplyr::filter(Geography != params$state, Geography != "United States") |>
  dplyr::mutate(govfunding = as.numeric(
    gsub("[%]", "", `Share of 990 filers with government grants at risk`)
  )) |>
  dplyr::arrange(desc(govfunding)) |>
  dplyr::slice_head(n = 3) |>
  dplyr::pull(Geography)

topdistricts_atrisk <- district |>
  dplyr::filter(Geography != params$state, Geography != "United States") |>
  dplyr::mutate(govfunding = as.numeric(
    gsub("[%]", "", `Share of 990 filers with government grants at risk`)
  )) |>
  dplyr::arrange(desc(govfunding)) |>
  dplyr::slice_head(n = 3) |>
  dplyr::pull(Geography)

topcounties_grants <- paste(topcounties_grants, collapse = ", ")
topcounties_surplus <- paste(topcounties_surplus, collapse = ", ")
topcounties_atrisk <- paste(topcounties_atrisk, collapse = ", ")

topcounties_grants <- gsub(",([^,]*)$", ", and\\1", topcounties_grants)
topcounties_grants <- gsub(" County", "", topcounties_grants)
topcounties_surplus <- gsub(",([^,]*)$", ", and\\1", topcounties_surplus)
topcounties_surplus <- gsub(" County", "", topcounties_surplus)
topcounties_atrisk <- gsub(",([^,]*)$", ", and\\1", topcounties_atrisk)
topcounties_atrisk <- gsub(" County", "", topcounties_atrisk)

topdistricts_grants <- format_districts(topdistricts_grants)
topdistricts_surplus <- format_districts(topdistricts_surplus)
topdistricts_atrisk <- format_districts(topdistricts_atrisk)
```

```{r, echo=FALSE}
if (state_title != "District of Columbia"){
  text <- glue::glue(
    "In {state_title}, nonprofits received a total of ${total_govgrants} in government grants. Nonprofits in {topcounties_grants} counties {topdistricts_grants} received the most government funding. Nonprofits in {topcounties_surplus} counties {topdistricts_surplus} would have the biggest gap to fill if they lost their government grants. Nonprofits in {topcounties_atrisk} counties {topdistricts_atrisk} have the highest share of nonprofits at risk of not covering their expenses if they lost their government grants."
  )
} else {
  text <- glue::glue("In the District of Columbia, nonprofits received a total of ${total_govgrants} in government grants.")
}
```

```{epoxy}
{text}
```

```{r formatting, echo=FALSE}
county <- format_percentages(county, 
                             "Share of 990 filers with government grants at risk",
                             "formatted_percentages")
district <- format_percentages(district, 
                               "Share of 990 filers with government grants at risk",
                               "formatted_percentages")
size <- format_percentages(size,
                           "Share of 990 filers with government grants at risk",
                           "formatted_percentages")
subsector <- format_percentages(subsector,
                                "Share of 990 filers with government grants at risk",
                                "formatted_percentages")
```


## {.tabset}

### Counties
```{r}
county |>
  dplyr::distinct() |>
  dplyr::mutate(Geography = factor(Geography)) |>
  dplyr::mutate(color = "") |>
  gt() |>
  data_color(
    columns = formatted_percentages,
    target_columns = color,
    method = "auto",
    palette = c(
      "#FFF2CF",
      "#FCE39E",
      "#FDD870",
      "#FCCB41",
      "#FDBF11",
      "#E88E2D",
      "#CA5800",
      "#843215"
    )
  ) |>
  cols_hide(formatted_percentages) |>
  cols_width(color ~ px(5)) |>
  cols_label(color = "") |>
  cols_align(align = "left", columns = c("Geography")) |>
  tab_style(
    style = cell_borders(
      sides = "right",
      color = "#d2d2d2",
      weight = px(1)
    ),
    locations = cells_body(columns = 1)
  ) |>
  tab_style(
    style = cell_text(weight = "bold"),
    locations = list(cells_body(columns = 1), cells_column_labels())
  ) |>
  tab_options(table.border.top.style = "hidden",
              data_row.padding = px(10))

```

### Congressional districts
```{r}
district |> 
  dplyr::mutate(color = "") |>
  gt() |>
  data_color(
    columns = formatted_percentages,
    target_columns = color,
    method = "auto",
    palette = c(
      "#FFF2CF",
      "#FCE39E",
      "#FDD870",
      "#FCCB41",
      "#FDBF11",
      "#E88E2D",
      "#CA5800",
      "#843215"
    )
  ) |>
  cols_hide(formatted_percentages) |>
  cols_width(color ~ px(5)) |>
  cols_label(color = "") |>
  cols_align(align = "left", columns = c("Geography")) |>
  tab_style(
    style = cell_borders(
      sides = "right",
      color = "#d2d2d2",
      weight = px(1)
    ),
    locations = cells_body(columns = 1)
  ) |>
  tab_style(
    style = cell_text(weight = "bold"),
    locations = list(cells_body(columns = 1), cells_column_labels())
  ) |>
  tab_options(table.border.top.style = "hidden",
              data_row.padding = px(10))
```

### Size
```{r}
size |> mutate(Size = factor(
  Size,
  levels = c(
    "Less than $100K",
    "$100K to $499K",
    "$500K to $999K",
    "$1M to $4.9M",
    "$5M to $9.9M",
    "$10M or more",
    "Total"
  )
)) |>
  arrange(Size) |>
   dplyr::mutate(color = "") |>
  gt() |>
  data_color(
    columns = `Share of 990 filers with government grants at risk`,
    target_columns = color,
    method = "auto",
    palette = c("#FFF2CF", "#FCE39E", "#FDD870", "#FCCB41", "#FDBF11", "#E88E2D", "#CA5800", "#843215")
    ) |>
  cols_hide(formatted_percentages) |>
    cols_width(color ~ px(5)) |>
  cols_label(
    color = ""  # This sets the column name to an empty string
) |>
  cols_align(
    align = "left",
    columns = c("Size")
  ) |>
  tab_style(
    style = cell_borders(
      sides = "right",
      color = "#d2d2d2",
      weight = px(1)
    ),
    locations = cells_body(
      columns = 1
    )
  ) |>
  tab_style(
    style = cell_text(weight = "bold"),
    locations = list(
      cells_body(columns = 1),  # First column
      cells_column_labels()      # All headers
    )
  ) |>
  tab_options(
    table.border.top.style = "hidden",
    data_row.padding = px(10)
  )
```

### Subsector
```{r}
subsector |> mutate(Subsector = factor(
  Subsector,
  levels = c(
        "Arts, culture, and humanities",
        "Education",
        "Environment and animals",
        "Health",
        "Hospitals",
        "Human services",
        "International, foreign affairs",
        "Public, societal benefit",
        "Religion-related",
        "Mutual/membership benefit",
        "Universities",
        "Unclassified",
        "Total"
      )
)) |>
  arrange(Subsector) |>
  dplyr::mutate(color = "") |>
  gt() |>
  data_color(
    columns = formatted_percentages,
    target_columns = color,
    method = "auto",
    palette = c(
      "#FFF2CF",
      "#FCE39E",
      "#FDD870",
      "#FCCB41",
      "#FDBF11",
      "#E88E2D",
      "#CA5800",
      "#843215"
    )
  ) |>
  cols_hide(formatted_percentages) |>
  cols_width(color ~ px(5)) |>
  cols_label(color = "") |>
  cols_align(align = "left", columns = c("Subsector")) |>
  tab_style(
    style = cell_borders(
      sides = "right",
      color = "#d2d2d2",
      weight = px(1)
    ),
    locations = cells_body(columns = 1)
  ) |>
  tab_style(
    style = cell_text(weight = "bold"),
    locations = list(cells_body(columns = 1), cells_column_labels())
  ) |>
  tab_options(table.border.top.style = "hidden",
              data_row.padding = px(10))
```

## {-}

###### **Notes**: Operating surplus reported as the median.

###### **Source**: National Center for Charitable Statistics 2021 501(c)(3) Charities [E-file Data](https://nccs.urban.org/nccs/datasets/efile/).